from pathlib import Path
from threading import Lock, Thread
from typing import Callable

from src.Agents.Brain.ToolLLM import ToolLLM
from src.Agents.Messages.Messages import SystemMessage, UserMessage, AIMessage
from src.Agents.Tools.ToolExecutor import ToolExecutor
from src.Logging.Logger import Logger


class Agent:
    @staticmethod
    def get_default_agent_name() -> str:
        return 'Agent'

    @staticmethod
    def get_default_agent_system_prompt() -> str:
        default_agent_system_prompt_file_path: Path = Path(__file__).parent / 'default_agent_system_prompt.md'
        return default_agent_system_prompt_file_path.read_text(encoding='utf-8')

    class ShouldPause(Exception):
        pass

    def __init__(
            self,
            llm: ToolLLM,
            logger: Logger,
            tool_executor: ToolExecutor,
            name: str | None = None,
            description: str | None = None,
            instructions: str | None = None
    ):
        # LLM
        self.llm: ToolLLM = llm

        # Logger
        self.logger: Logger = logger

        # Tool Manager
        self.tool_executor: ToolExecutor = tool_executor

        # Name
        self.name: str = name or Agent.get_default_agent_name()

        # Description
        self.description: str = description or ''

        # System prompt
        self.instructions = SystemMessage(instructions or Agent.get_default_agent_system_prompt())

        # Message history
        self.message_history: list = [self.instructions]
        self.message_history_lock: Lock = Lock()

        # Task queue -> only use append and pop(0) !!!
        self.current_task: str | None = None
        self.tasks: list[tuple[str, Callable[[str], None], Callable[[str], None]]] = []
        self.tasks_lock: Lock = Lock()

        # Function for submitting answers. It is permanently stored so that it can be used in resume situations
        self.submit_final_answer: Callable[[str], None] = lambda _ : None
        self.submit_partial_answer: Callable[[str], None] = lambda _ : None

        # Working state
        self.working: bool = False
        self.working_state_lock: Lock = Lock()
        self.should_pause: bool = False

    def __is_working(self) -> bool:
        return self.working

    def __set_working_state(self, working: bool) -> None:
        """
        This always clears the should_pause flag when called,
        no matter the argument given
        """
        with self.working_state_lock:
            self.working = working
            self.should_pause = False

    def __add_task(
            self, task: str,
            submit_final_answer: Callable[[str], None] = lambda _ : None,
            submit_partial_answer: Callable[[str], None] = lambda _ : None
    ) -> None:
        if not task:
            return
        with self.tasks_lock:
            self.tasks.append((task, submit_final_answer, submit_partial_answer))

    def __get_next_task(self) -> tuple[str | None, Callable[[str], None], Callable[[str], None]]:
        with self.tasks_lock:
            if not self.tasks:
                return None, lambda _ : None, lambda _ : None
            return self.tasks.pop(0)

    def __handle_ai_message(self, ai_message: AIMessage) -> None:
        log_message: str = (
            f'task:\n{self.current_task}'
            f'\n\n'
            f'response:\n{ai_message.get_content()}'
            f'\n\n'
            f'tool calls: {[tool_call.get_tool_name() for tool_call in ai_message.get_tool_calls()]}'
        )
        self.logger.log(log_message, who=self.name, use_separator=True, use_timestamp=True)

        if ai_message.is_partial():
            self.submit_partial_answer(ai_message.content)
        else:
            self.submit_final_answer(ai_message.content)
            self.current_task = None

    def __complete_chat(self) -> AIMessage:
        # Check if the execution should pause
        with self.working_state_lock:
            if self.should_pause:
                raise self.ShouldPause

        # Both appends to the message history and returns the next message generated by AI
        # This is only one iteration of invoking the llm
        # It doesn't run any tools, just generates an answer that might contain tool calls or just plain content
        # There is no loop in this function

        ai_message: AIMessage = self.llm.complete_chat(self.message_history)
        self.message_history.append(ai_message)

        self.__handle_ai_message(ai_message)

        return ai_message

    def __complete_chat_until_no_tools_are_called(self) -> None:
        ai_message: AIMessage = self.__complete_chat()

        while ai_message.is_partial():
            for tool_call in ai_message.get_tool_calls():
                self.message_history.append(self.tool_executor.call_tool(tool_call))

            ai_message = self.__complete_chat()

    def __resume_last_task_if_not_complete(self) -> None:
        if not self.current_task:
            return

        with self.message_history_lock:
            self.__complete_chat_until_no_tools_are_called()

    def __solve_task(self, task: str) -> None:
        self.current_task = task

        with self.message_history_lock:
            self.message_history.append(UserMessage(task))
            self.__complete_chat_until_no_tools_are_called()

    def __start_work(self) -> None:
        def work() -> None:
            if self.__is_working():
                return
            self.__set_working_state(True)

            try:
                self.__resume_last_task_if_not_complete()

                next_task, self.submit_final_answer, self.submit_partial_answer = self.__get_next_task()
                while next_task:
                    self.__solve_task(next_task)
                    next_task, self.submit_final_answer, self.submit_partial_answer = self.__get_next_task()

            except self.ShouldPause as _:
                pass

            self.__set_working_state(False)

        Thread(target=work, daemon=True).start()

    # PUBLIC

    def get_id(self) -> str:
        return self.name.lower().replace(' ', '_')

    def give_task(
            self, task: str,
            submit_final_answer: Callable[[str], None] = lambda _ : None,
            submit_partial_answer: Callable[[str], None] = lambda _ : None
    ) -> None:
        if not task:
            return
        self.__add_task(task, submit_final_answer, submit_partial_answer)

        if not self.__is_working():
            self.__start_work()

    def pause_work(self) -> None:
        with self.working_state_lock:
            if not self.__is_working():
                return
            self.should_pause = True

    def resume_work(self) -> None:
        self.__start_work()

    def clear_history(self) -> None:
        self.pause_work()
        with self.message_history_lock:
            with self.tasks_lock:
                self.message_history.clear()
                self.message_history.append(self.instructions)
                self.tasks.clear()
